
<html>
<head>
    <title>ExtJS with Laminas</title>
    <link rel="stylesheet" type="text/css" href="/js/extjsstarter/js/libraries/extjs/classic/theme-neptune/resources/theme-neptune-all.css">
    <script type="text/javascript" src="/js/extjsstarter/js/libraries/extjs/ext-all.js"></script>
    <script type="text/javascript" src="/js/extjsstarter/js/app/app.js"></script>
</head>
<body data-module="App.User">
</body>
</html>

